rules:
  unpinned-uses:
    config:
      policies:
        "actions/*": ref-pin
        "exasol/python-toolbox/.github/actions/security-issues": ref-pin
        "*": hash-pin
  cache-poisoning:
    ignore:
      # Enabling caching is OK for non-release workflows
      - ci-build.yml
      - ci-build-native-build.yml
      - ci-build-db-version-matrix.yml
      - project-keeper-verify.yml
      - test_on_windows.yml
      - test_linux_build_on_windows.yml
  obfuscation:
    ignore:
      # Generated workflows use boolean conditions like ${{ false }}
      - ci-build.yml
      - release.yml
      - project-keeper-verify.yml # workaround for https://github.com/exasol/project-keeper/issues/734
  secrets-inherit:
    ignore:
      # Required for passing slack webhooks
      - ci-build.yml
      - ci-build-db-version-matrix.yml
      - dependencies_check.yml
      - release.yml
