sources:
  - type: maven
    path: server/pom.xml
    modules:
      - jar_artifact
      - integration_tests
  - type: golang
    path: go-client/go.mod
linkReplacements:
  - https://javalin.io/javalin|https://javalin.io/
version: 0.3.9
excludes:
  # We use release-droid until PK supports Go projects
  - "E-PK-CORE-26: '.github/workflows/release_droid_prepare_original_checksum.yml' exists but must not exist. Reason: Release-droid workflows are replaced by release.yml"
  - "E-PK-CORE-26: '.github/workflows/release_droid_print_quick_checksum.yml' exists but must not exist. Reason: Release-droid workflows are replaced by release.yml"
  - "E-PK-CORE-26: '.github/workflows/release_droid_upload_github_release_assets.yml' exists but must not exist. Reason: Release-droid workflows are replaced by release.yml"
  - "E-PK-CORE-26: 'release_config.yml' exists but must not exist. Reason: Release-droid configuration is replaced by release.yml"
