sources:
  - type: maven
    path: server/pom.xml
    modules:
      - jar_artifact
      - integration_tests
  - type: golang
    path: go-client/go.mod
version: 0.2.0
linkReplacements:
  - https://javalin.io/javalin|https://javalin.io/
